name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: '1.20'

jobs:
  # verify-go-mod:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ env.GO_VERSION }}
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Check go mod
  #       run: |
  #         go mod tidy
  #         git diff --exit-code go.mod
  # lint:
  #   name: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ env. GO_VERSION }}
  #     - uses: actions/checkout@v3
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.51.1
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env. GO_VERSION }}
      - uses: actions/checkout@v3
      - name: Go test
        run: |
          make ci-init
          make ci-test-integration
  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ env. GO_VERSION }}
  #     - uses: actions/checkout@v3
  #     - name: Go test
  #       run: |
  #         make test
